version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: bbit
      POSTGRES_PASSWORD: bbitpass
      POSTGRES_DB: bbitdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://bbit:bbitpass@db:5432/bbitdb
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
